### ISSUE TITLE
Can not run MPI on android devices

### ISSUE THREAD

**Issue by anhtran1010** [Collegeville/Tran-Anh-Work#2]
Doctor @maherou ,

How could I run HPCG without MPI since Android does not support it?

**Comment by maherou** [comment]
@anhtran1010: Look at the INSTALL file.  It has instructions for this option and others: https://github.com/hpcg-benchmark/hpcg/blob/master/INSTALL

In the file, you will see these lines:

```
* Compile with MPI disabled::

    -DHPCG_NO_MPI

* Compile without OpenMP enabled::

    -DHPCG_NO_OPENMP
```
